#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_waifu_test = env_modules.Clone()

module_obj = []

env_waifu_test.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
