/**************************************************************************/
/*  box3d_physics_server_3d_todo.cpp                                      */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// Generated by the box3d stub generator - do not hand-edit.
//
// Every function here is an entry point the Box3D backend has not implemented
// yet. Implement one in box3d_physics_server_3d.cpp, re-run the generator, and its stub leaves this
// file. When this file holds nothing, that class is feature-complete.

#include "box3d_physics_server_3d.h"
#include "box3d_todo.h"

RID Box3DPhysicsServer3D::world_boundary_shape_create() {
	B3_TODO();
	return RID();
}

RID Box3DPhysicsServer3D::separation_ray_shape_create() {
	B3_TODO();
	return RID();
}

RID Box3DPhysicsServer3D::heightmap_shape_create() {
	B3_TODO();
	return RID();
}

RID Box3DPhysicsServer3D::custom_shape_create() {
	B3_TODO();
	return RID();
}

void Box3DPhysicsServer3D::shape_set_custom_solver_bias(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::shape_get_custom_solver_bias(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::space_set_debug_contacts(RID, int) {
	B3_TODO();
}

Vector<Vector3> Box3DPhysicsServer3D::space_get_contacts(RID) const {
	B3_TODO();
	return Vector<Vector3>();
}

int Box3DPhysicsServer3D::space_get_contact_count(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::body_set_collision_priority(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::body_get_collision_priority(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::body_set_user_flags(RID, uint32_t) {
	B3_TODO();
}

uint32_t Box3DPhysicsServer3D::body_get_user_flags(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::body_set_force_integration_callback(RID, const Callable &, const Variant &) {
	B3_TODO();
}

RID Box3DPhysicsServer3D::soft_body_create() {
	B3_TODO();
	return RID();
}

void Box3DPhysicsServer3D::soft_body_update_rendering_server(RID, RequiredParam<PhysicsServer3DRenderingServerHandler> rp_rendering_server_handler) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_set_space(RID, RID) {
	B3_TODO();
}

RID Box3DPhysicsServer3D::soft_body_get_space(RID) const {
	B3_TODO();
	return RID();
}

void Box3DPhysicsServer3D::soft_body_set_mesh(RID, RID) {
	B3_TODO();
}

AABB Box3DPhysicsServer3D::soft_body_get_bounds(RID) const {
	B3_TODO();
	return AABB();
}

void Box3DPhysicsServer3D::soft_body_set_collision_layer(RID, uint32_t) {
	B3_TODO();
}

uint32_t Box3DPhysicsServer3D::soft_body_get_collision_layer(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_collision_mask(RID, uint32_t) {
	B3_TODO();
}

uint32_t Box3DPhysicsServer3D::soft_body_get_collision_mask(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_add_collision_exception(RID, RID) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_remove_collision_exception(RID, RID) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_get_collision_exceptions(RID, List<RID> *) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_set_state(RID, BodyState, const Variant &) {
	B3_TODO();
}

Variant Box3DPhysicsServer3D::soft_body_get_state(RID, BodyState) const {
	B3_TODO();
	return Variant();
}

void Box3DPhysicsServer3D::soft_body_set_transform(RID, const Transform3D &) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_set_ray_pickable(RID, bool) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_set_simulation_precision(RID, int) {
	B3_TODO();
}

int Box3DPhysicsServer3D::soft_body_get_simulation_precision(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_total_mass(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::soft_body_get_total_mass(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_linear_stiffness(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::soft_body_get_linear_stiffness(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_shrinking_factor(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::soft_body_get_shrinking_factor(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_pressure_coefficient(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::soft_body_get_pressure_coefficient(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_damping_coefficient(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::soft_body_get_damping_coefficient(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_set_drag_coefficient(RID, real_t) {
	B3_TODO();
}

real_t Box3DPhysicsServer3D::soft_body_get_drag_coefficient(RID) const {
	B3_TODO();
	return 0;
}

void Box3DPhysicsServer3D::soft_body_move_point(RID, int, const Vector3 &) {
	B3_TODO();
}

Vector3 Box3DPhysicsServer3D::soft_body_get_point_global_position(RID, int) const {
	B3_TODO();
	return Vector3();
}

void Box3DPhysicsServer3D::soft_body_apply_point_impulse(RID, int, const Vector3 &) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_apply_point_force(RID, int, const Vector3 &) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_apply_central_impulse(RID, const Vector3 &) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_apply_central_force(RID, const Vector3 &) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_remove_all_pinned_points(RID) {
	B3_TODO();
}

void Box3DPhysicsServer3D::soft_body_pin_point(RID, int, bool) {
	B3_TODO();
}

bool Box3DPhysicsServer3D::soft_body_is_point_pinned(RID, int) const {
	B3_TODO();
	return false;
}
