/**************************************************************************/
/*  box3d_direct_body_state_3d_todo.cpp                                   */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// Generated by the box3d stub generator - do not hand-edit.
//
// Every function here is an entry point the Box3D backend has not implemented
// yet. Implement one in box3d_direct_body_state_3d.cpp, re-run the generator, and its stub leaves this
// file. When this file holds nothing, that class is feature-complete.

#include "box3d_direct_body_state_3d.h"
#include "box3d_todo.h"

Vector3 Box3DDirectBodyState3D::get_center_of_mass() const {
	B3_TODO();
	return Vector3();
}

Vector3 Box3DDirectBodyState3D::get_center_of_mass_local() const {
	B3_TODO();
	return Vector3();
}

Basis Box3DDirectBodyState3D::get_principal_inertia_axes() const {
	B3_TODO();
	return Basis();
}

Vector3 Box3DDirectBodyState3D::get_inverse_inertia() const {
	B3_TODO();
	return Vector3();
}

Basis Box3DDirectBodyState3D::get_inverse_inertia_tensor() const {
	B3_TODO();
	return Basis();
}

Vector3 Box3DDirectBodyState3D::get_velocity_at_local_position(const Vector3 &) const {
	B3_TODO();
	return Vector3();
}

void Box3DDirectBodyState3D::add_constant_central_force(const Vector3 &) {
	B3_TODO();
}

void Box3DDirectBodyState3D::add_constant_force(const Vector3 &, const Vector3 &) {
	B3_TODO();
}

void Box3DDirectBodyState3D::add_constant_torque(const Vector3 &) {
	B3_TODO();
}

void Box3DDirectBodyState3D::set_constant_force(const Vector3 &) {
	B3_TODO();
}

Vector3 Box3DDirectBodyState3D::get_constant_force() const {
	B3_TODO();
	return Vector3();
}

void Box3DDirectBodyState3D::set_constant_torque(const Vector3 &) {
	B3_TODO();
}

Vector3 Box3DDirectBodyState3D::get_constant_torque() const {
	B3_TODO();
	return Vector3();
}

void Box3DDirectBodyState3D::set_collision_layer(uint32_t) {
	B3_TODO();
}

uint32_t Box3DDirectBodyState3D::get_collision_layer() const {
	B3_TODO();
	return 0;
}

void Box3DDirectBodyState3D::set_collision_mask(uint32_t) {
	B3_TODO();
}

uint32_t Box3DDirectBodyState3D::get_collision_mask() const {
	B3_TODO();
	return 0;
}

int Box3DDirectBodyState3D::get_contact_count() const {
	B3_TODO();
	return 0;
}

Vector3 Box3DDirectBodyState3D::get_contact_local_position(int) const {
	B3_TODO();
	return Vector3();
}

Vector3 Box3DDirectBodyState3D::get_contact_local_normal(int) const {
	B3_TODO();
	return Vector3();
}

Vector3 Box3DDirectBodyState3D::get_contact_impulse(int) const {
	B3_TODO();
	return Vector3();
}

int Box3DDirectBodyState3D::get_contact_local_shape(int) const {
	B3_TODO();
	return 0;
}

Vector3 Box3DDirectBodyState3D::get_contact_local_velocity_at_position(int) const {
	B3_TODO();
	return Vector3();
}

RID Box3DDirectBodyState3D::get_contact_collider(int) const {
	B3_TODO();
	return RID();
}

Vector3 Box3DDirectBodyState3D::get_contact_collider_position(int) const {
	B3_TODO();
	return Vector3();
}

ObjectID Box3DDirectBodyState3D::get_contact_collider_id(int) const {
	B3_TODO();
	return ObjectID();
}

int Box3DDirectBodyState3D::get_contact_collider_shape(int) const {
	B3_TODO();
	return 0;
}

Vector3 Box3DDirectBodyState3D::get_contact_collider_velocity_at_position(int) const {
	B3_TODO();
	return Vector3();
}
